# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Norcx's Blog
subtitle: A Blog to share CS and AI
description: This is my personal blog.
author: Norcx
language: zh-CN
timezone: Asia/Shanghai
keywords: "Computer Science, Artificial Intelligence, Programming, Technology"

# URL
url: https://norcx.github.io
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
syntax_highlighter: highlight.js
highlight:
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
index_generator:
  path: ''
  per_page: 12
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
meta_generator: true

# Date / Time format
date_format: YYYY-MM-DD
time_format: HH:mm:ss
updated_option: 'mtime'

# Pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
include:
exclude:
ignore:

# Extensions
theme: hexo-theme-matery

# Deployment
deploy:
  type: git
  repo: https://github.com/norcx/norcx.github.io.git
  branch: main

# Social media integration
social:
  GitHub: https://github.com/norcx
  Email: mailto:norcx@qq.com

# Google Analytics (uncomment and replace with your actual tracking ID)
# google_analytics: 'UA-XXXXX-X'

permalink_pinyin:
  enable: true
  separator: '-' # default: '-'
